[package]
name = "rgb_node"
description = "RGB node"
version = "0.1.0-rc.1"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "layer-2", "smart-contracts", "rgb"]
edition = "2018"
readme = "README.md"

[lib]
name = "rgb"

[dependencies]
amplify = "~1.2.0"
amplify_derive = "~1.2.0"
base64 = "0.12"
dotenv = "~0.15.0"
clap = "=3.0.0-beta.2"
chrono = { version = "~0.4.11", features = [ "serde" ] }
serde = { version = "~1.0.111", features = ["derive"] }
serde_with = "~1.5.0"
serde_json = "~1.0.55"
serde_yaml = "~0.8.13"
toml = "~0.5.6"
bech32 = "~0.7.2"
log = { version = "~0.4", features = ["max_level_trace", "release_max_level_debug"] }
async-trait = "~0.1.35"
regex = "~1.3.9"
env_logger = "~0.7.1"
num-traits = "~0.2.12"
num-derive = "~0.3.0"
url = "~2.1.1"
tokio = { version = "~0.2.21", features = ["full"] }
futures = "~0.3.5"
zmq = "~0.9.2"
tiny_http = "~0.7.0"
prometheus = "~0.9.0"
electrum-client = "=0.3.0-beta.1"

[dependencies.lnpbp]
git = "https://github.com/LNP-BP/rust-lnpbp"
tag = "v0.1.0-rc.1"
features = ["all"]

[dependencies.lnpbp_derive]
git = "https://github.com/LNP-BP/rust-lnpbp"
tag = "v0.1.0-rc.1"

[target.'cfg(target_os="android")'.dependencies.zmq]
version = "~0.9"
features = ["vendored"]

[features]
default = ["daemon", "fungibles", "collectibles", "identities"]
service = []
daemon = ["service"]
cli = []
fungibles = []
collectibles = []
identities = []

[workspace]
members = [".", "ffi"]
default-members = ["."]

[patch.crates-io]
# We need this b/c of breaking change in tagged hash type generation
bitcoin_hashes = { git = "https://github.com/LNP-BP/bitcoin_hashes", tag = "lnpbp-v0.1.0-rc1" }
bitcoin = { git = "https://github.com/LNP-BP/rust-bitcoin", tag = "lnpbp-v0.1.0-rc1" }
# We need custom branches here just to depend on the same bitcoin master and do
# not have secp256k1 version conflict
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", tag = "lnpbp-v0.1.0-rc1" }
# Remove this once https://github.com/teawithsand/torut/pull/5 got merged
# Remove this once https://github.com/jean-airoldie/zeromq-src-rs/pull/15 got merged
zeromq-src = { git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake" }
