[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["Alekos Filini <@afilini>"]

[dependencies]
clap = "~2.32.0"
bitcoin = "~0.14.2"
strason = "0.4"
jsonrpc = { git = "https://github.com/apoelstra/rust-jsonrpc.git", tag = "0.9.0" }
rgb = { git = "https://github.com/rgb-org/rgb.git", branch = "pay-to-contract" }
secp256k1 = "~0.11.2"

[dependencies.hyper]
version = "0.9.18"
default-features = false

[features]
default = []
ssl = ["hyper/ssl"]